### PR TITLE
Handle deleted state of che helm chart by rollbacking or purging the charts

### LINKED ISSUE #18: Command server:start fails if che helm chart has status DELETE or DELETING
If Che Helm Chart is in `DELETING` status: 

```
$ helm list --all
NAME	REVISION	UPDATED                 	STATUS  	CHART    	APP VERSION	NAMESPACE
che 	1       	Tue Dec 11 19:57:47 2018	DELETING	che-0.1.0	           	kube-che
```

and the command server:start is executed the following error is shown:

```
  ✔ Verify if namespace kube-che exist
  ↓ Verify if Che server is already running [skipped]
    → Che namespace doesn't exist.
  ✖ Deploy Che Server
    → Error: UPGRADE FAILED: "che" has no deployed releases
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: /bin/sh -c helm upgrade /
                            --install che /
                            --namespace kube-che /
                            --set global.ingressDomain=$(minikube ip).nip.io /
                            --set cheImage=eclipse/che-server:nightly /
                            --set global.cheWorkspacesNamespace=kube-che /
                            /Users/mloriedo/Library/Caches/chectl/templates/kubernetes/helm/che/
Error: UPGRADE FAILED: "che" has no deployed releases
    at makeError (~/github/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/github/chectl/node_modules/execa/index.js:278:16)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by benoitf**
Fix #18

`$ helm history` will display now
```shell
29      	Wed Jul  3 11:00:29 2019	SUPERSEDED	che-0.1.0	Rollback to 28   
30      	Wed Jul  3 11:00:30 2019	DEPLOYED  	che-0.1.0	Upgrade complete 
```

Change-Id: I30a7e4462d5c10219c216ee528e73f2853aeaba5
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

File: src/installers/helm.ts [hunk 1]
```diff
@@ -163,7 +163,21 @@ error: E_COMMAND_FAILED`)
     }
 
     let command = `helm upgrade --install che --force --namespace ${flags.chenamespace} --set global.ingressDomain=${flags.domain} --set cheImage=${flags.cheimage} --set global.cheWorkspacesNamespace=${flags.chenamespace} ${multiUserFlag} ${tlsFlag} ${destDir}`
-    await execa.shell(command, { timeout: execTimeout })
+    let {code} = await execa.shell(command, { timeout: execTimeout, reject: false })
+    // if process failed, check the following
+    // if revision=1, purge and retry command else rollback
+    if (code !== 0) {
+      // get revision
+      const {stdout} = await execa.shell(`helm history ${flags.chenamespace} | tail -1 | head -1 | awk '{print $1}'`, { timeout: execTimeout })
```
Comment (benoitf) [inline src/installers/helm.ts]: I realize it won't work on windows

Comment (benoitf) [reply src/installers/helm.ts]: reworked to use a json output
